apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: muthuraj07/gitapp:11
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

